# Generated by Django 5.0.4 on 2024-04-16 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_alter_achat_id_alter_administrateur_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='fournisseur',
        ),
        migrations.DeleteModel(
            name='Fournisseur',
        ),
    ]
